### ISSUE TITLE
Question: Can't click files to see diff with line-by-line

### ISSUE THREAD

**Issue by ACoolmanBigHealth** [eugenezinovyev/lcov-viewer#25]
Hi great looking report, 

[This image](https://user-images.githubusercontent.com/1678896/139162954-4e062a3a-9776-4b15-9700-2a63dbdd58c3.gif) shows files as pink links. 

But when I load my lcov my fines are not links, so I can't click them.

Also, I don't quite understand how to run the cli or the report

```
lcov-viewer lcov -o ./output-dir ./coverage/lcov.info

```
Results in 
```
env: node\r: No such file or directory
error Command failed with exit code 127
```

**Comment by eugenezinovyev** [comment]
Hello, thank you!

The LCOV file does not contain any sources code on it's own. So that the CLI tool is only capable to build percentage tree only.
I you want to get full report after tests run you need to install Istanbul reporter package: https://github.com/eugenezinovyev/lcov-viewer/tree/main/packages/istanbul-report

Regarding the way to run CLI:
The tool tries to find input file relative to the current working directory. Does `./coverage/lcov.info` exist?
